// The resume builder's fonts: FlowCV's list (sans, serif, mono, and creative fonts for the name),
// bundled from @fontsource (OFL-1.1) and loaded by the builder page only, plus the standard fonts
// of the computer. Bundled fonts look the same on every computer and in every saved PDF.
// Keys are stored in resumes: add new ones, never rename or remove one.

import { FONT_KEYS, NAME_ONLY_FONT_KEYS, type AnyFontKey, type FontKey } from './fontKeys';

/** Only Ethiopic characters (Amharic and others); bundled, and declared for that range only, so it
 * can sit in every stack without taking over Latin text when a font is missing. */
const ETHIOPIC = "'Noto Sans Ethiopic'";

export { FONT_KEYS, NAME_ONLY_FONT_KEYS, type AnyFontKey, type FontKey };

export type FontGroup = 'sans' | 'serif' | 'mono' | 'standard' | 'creative';
export const FONT_GROUP_LABELS: Record<FontGroup, string> = {
  sans: 'Sans serif',
  serif: 'Serif',
  mono: 'Monospace',
  standard: "Your computer's fonts",
  creative: 'Creative (name only)',
};

export interface FontDef {
  label: string;
  /** The first family in the stack, to load it before measuring pages. */
  family: string;
  /** Shipped with the extension (the same everywhere) or the computer's own. */
  bundled: boolean;
  group: FontGroup;
  /** Has a real bold (700 or heavier); otherwise the name uses the regular weight. */
  bold: boolean;
  italic: boolean;
  stack: string;
}

export const FONTS: Record<AnyFontKey, FontDef> = {
  'public-sans': {
    label: 'Public Sans',
    family: 'Public Sans Variable',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Public Sans Variable', 'Public Sans', Arial, ${ETHIOPIC}, sans-serif`,
  },
  helvetica: {
    label: 'Helvetica / Arial',
    family: 'Helvetica Neue',
    bundled: false,
    group: 'standard',
    bold: true,
    italic: true,
    stack: `'Helvetica Neue', Helvetica, Arial, ${ETHIOPIC}, sans-serif`,
  },
  georgia: {
    label: 'Georgia',
    family: 'Georgia',
    bundled: false,
    group: 'standard',
    bold: true,
    italic: true,
    stack: `Georgia, 'Times New Roman', ${ETHIOPIC}, serif`,
  },
  palatino: {
    label: 'Palatino',
    family: 'Palatino Linotype',
    bundled: false,
    group: 'standard',
    bold: true,
    italic: true,
    stack: `'Palatino Linotype', Palatino, 'Book Antiqua', ${ETHIOPIC}, serif`,
  },
  garamond: {
    label: 'Garamond',
    family: 'Garamond',
    bundled: false,
    group: 'standard',
    bold: true,
    italic: true,
    stack: `Garamond, 'EB Garamond', ${ETHIOPIC}, serif`,
  },
  times: {
    label: 'Times',
    family: 'Times New Roman',
    bundled: false,
    group: 'standard',
    bold: true,
    italic: true,
    stack: `'Times New Roman', Times, ${ETHIOPIC}, serif`,
  },
  verdana: {
    label: 'Verdana',
    family: 'Verdana',
    bundled: false,
    group: 'standard',
    bold: true,
    italic: true,
    stack: `Verdana, Geneva, ${ETHIOPIC}, sans-serif`,
  },
  trebuchet: {
    label: 'Trebuchet',
    family: 'Trebuchet MS',
    bundled: false,
    group: 'standard',
    bold: true,
    italic: true,
    stack: `'Trebuchet MS', 'Lucida Grande', ${ETHIOPIC}, sans-serif`,
  },
  tahoma: {
    label: 'Tahoma',
    family: 'Tahoma',
    bundled: false,
    group: 'standard',
    bold: true,
    italic: true,
    stack: `Tahoma, Geneva, ${ETHIOPIC}, sans-serif`,
  },
  courier: {
    label: 'Courier',
    family: 'Courier New',
    bundled: false,
    group: 'standard',
    bold: true,
    italic: true,
    stack: `'Courier New', Courier, ${ETHIOPIC}, monospace`,
  },
  'source-sans-3': {
    label: 'Source Sans 3',
    family: 'Source Sans 3',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Source Sans 3', Arial, ${ETHIOPIC}, sans-serif`,
  },
  karla: {
    label: 'Karla',
    family: 'Karla',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Karla', Arial, ${ETHIOPIC}, sans-serif`,
  },
  mulish: {
    label: 'Mulish',
    family: 'Mulish',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Mulish', Arial, ${ETHIOPIC}, sans-serif`,
  },
  lato: {
    label: 'Lato',
    family: 'Lato',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Lato', Arial, ${ETHIOPIC}, sans-serif`,
  },
  'titillium-web': {
    label: 'Titillium Web',
    family: 'Titillium Web',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Titillium Web', Arial, ${ETHIOPIC}, sans-serif`,
  },
  'work-sans': {
    label: 'Work Sans',
    family: 'Work Sans',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Work Sans', Arial, ${ETHIOPIC}, sans-serif`,
  },
  barlow: {
    label: 'Barlow',
    family: 'Barlow',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Barlow', Arial, ${ETHIOPIC}, sans-serif`,
  },
  jost: {
    label: 'Jost',
    family: 'Jost',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Jost', Arial, ${ETHIOPIC}, sans-serif`,
  },
  'fira-sans': {
    label: 'Fira Sans',
    family: 'Fira Sans',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Fira Sans', Arial, ${ETHIOPIC}, sans-serif`,
  },
  roboto: {
    label: 'Roboto',
    family: 'Roboto',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Roboto', Arial, ${ETHIOPIC}, sans-serif`,
  },
  rubik: {
    label: 'Rubik',
    family: 'Rubik',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Rubik', Arial, ${ETHIOPIC}, sans-serif`,
  },
  asap: {
    label: 'Asap',
    family: 'Asap',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Asap', Arial, ${ETHIOPIC}, sans-serif`,
  },
  nunito: {
    label: 'Nunito',
    family: 'Nunito',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Nunito', Arial, ${ETHIOPIC}, sans-serif`,
  },
  'open-sans': {
    label: 'Open Sans',
    family: 'Open Sans',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'Open Sans', Arial, ${ETHIOPIC}, sans-serif`,
  },
  'ibm-plex-sans': {
    label: 'IBM Plex Sans',
    family: 'IBM Plex Sans',
    bundled: true,
    group: 'sans',
    bold: true,
    italic: true,
    stack: `'IBM Plex Sans', Arial, ${ETHIOPIC}, sans-serif`,
  },
  lora: {
    label: 'Lora',
    family: 'Lora',
    bundled: true,
    group: 'serif',
    bold: true,
    italic: true,
    stack: `'Lora', Georgia, ${ETHIOPIC}, serif`,
  },
  'source-serif-4': {
    label: 'Source Serif 4',
    family: 'Source Serif 4',
    bundled: true,
    group: 'serif',
    bold: true,
    italic: true,
    stack: `'Source Serif 4', Georgia, ${ETHIOPIC}, serif`,
  },
  'zilla-slab': {
    label: 'Zilla Slab',
    family: 'Zilla Slab',
    bundled: true,
    group: 'serif',
    bold: true,
    italic: true,
    stack: `'Zilla Slab', Georgia, ${ETHIOPIC}, serif`,
  },
  'pt-serif': {
    label: 'PT Serif',
    family: 'PT Serif',
    bundled: true,
    group: 'serif',
    bold: true,
    italic: true,
    stack: `'PT Serif', Georgia, ${ETHIOPIC}, serif`,
  },
  literata: {
    label: 'Literata',
    family: 'Literata',
    bundled: true,
    group: 'serif',
    bold: true,
    italic: true,
    stack: `'Literata', Georgia, ${ETHIOPIC}, serif`,
  },
  'eb-garamond': {
    label: 'EB Garamond',
    family: 'EB Garamond',
    bundled: true,
    group: 'serif',
    bold: true,
    italic: true,
    stack: `'EB Garamond', Georgia, ${ETHIOPIC}, serif`,
  },
  aleo: {
    label: 'Aleo',
    family: 'Aleo',
    bundled: true,
    group: 'serif',
    bold: true,
    italic: true,
    stack: `'Aleo', Georgia, ${ETHIOPIC}, serif`,
  },
  'crimson-pro': {
    label: 'Crimson Pro',
    family: 'Crimson Pro',
    bundled: true,
    group: 'serif',
    bold: true,
    italic: true,
    stack: `'Crimson Pro', Georgia, ${ETHIOPIC}, serif`,
  },
  'cormorant-garamond': {
    label: 'Cormorant Garamond',
    family: 'Cormorant Garamond',
    bundled: true,
    group: 'serif',
    bold: true,
    italic: true,
    stack: `'Cormorant Garamond', Georgia, ${ETHIOPIC}, serif`,
  },
  vollkorn: {
    label: 'Vollkorn',
    family: 'Vollkorn',
    bundled: true,
    group: 'serif',
    bold: true,
    italic: true,
    stack: `'Vollkorn', Georgia, ${ETHIOPIC}, serif`,
  },
  amiri: {
    label: 'Amiri',
    family: 'Amiri',
    bundled: true,
    group: 'serif',
    bold: true,
    italic: true,
    stack: `'Amiri', Georgia, ${ETHIOPIC}, serif`,
  },
  'crimson-text': {
    label: 'Crimson Text',
    family: 'Crimson Text',
    bundled: true,
    group: 'serif',
    bold: true,
    italic: true,
    stack: `'Crimson Text', Georgia, ${ETHIOPIC}, serif`,
  },
  alegreya: {
    label: 'Alegreya',
    family: 'Alegreya',
    bundled: true,
    group: 'serif',
    bold: true,
    italic: true,
    stack: `'Alegreya', Georgia, ${ETHIOPIC}, serif`,
  },
  inconsolata: {
    label: 'Inconsolata',
    family: 'Inconsolata',
    bundled: true,
    group: 'mono',
    bold: true,
    italic: false,
    stack: `'Inconsolata', 'Courier New', ${ETHIOPIC}, monospace`,
  },
  'source-code-pro': {
    label: 'Source Code Pro',
    family: 'Source Code Pro',
    bundled: true,
    group: 'mono',
    bold: true,
    italic: true,
    stack: `'Source Code Pro', 'Courier New', ${ETHIOPIC}, monospace`,
  },
  'ibm-plex-mono': {
    label: 'IBM Plex Mono',
    family: 'IBM Plex Mono',
    bundled: true,
    group: 'mono',
    bold: true,
    italic: true,
    stack: `'IBM Plex Mono', 'Courier New', ${ETHIOPIC}, monospace`,
  },
  'overpass-mono': {
    label: 'Overpass Mono',
    family: 'Overpass Mono',
    bundled: true,
    group: 'mono',
    bold: true,
    italic: false,
    stack: `'Overpass Mono', 'Courier New', ${ETHIOPIC}, monospace`,
  },
  'space-mono': {
    label: 'Space Mono',
    family: 'Space Mono',
    bundled: true,
    group: 'mono',
    bold: true,
    italic: true,
    stack: `'Space Mono', 'Courier New', ${ETHIOPIC}, monospace`,
  },
  'courier-prime': {
    label: 'Courier Prime',
    family: 'Courier Prime',
    bundled: true,
    group: 'mono',
    bold: true,
    italic: true,
    stack: `'Courier Prime', 'Courier New', ${ETHIOPIC}, monospace`,
  },
  comfortaa: {
    label: 'Comfortaa',
    family: 'Comfortaa',
    bundled: true,
    group: 'creative',
    bold: true,
    italic: false,
    stack: `'Comfortaa', ${ETHIOPIC}, cursive`,
  },
  'abril-fatface': {
    label: 'Abril Fatface',
    family: 'Abril Fatface',
    bundled: true,
    group: 'creative',
    bold: false,
    italic: false,
    stack: `'Abril Fatface', ${ETHIOPIC}, cursive`,
  },
  'amatic-sc': {
    label: 'Amatic SC',
    family: 'Amatic SC',
    bundled: true,
    group: 'creative',
    bold: true,
    italic: false,
    stack: `'Amatic SC', ${ETHIOPIC}, cursive`,
  },
  'bungee-shade': {
    label: 'Bungee Shade',
    family: 'Bungee Shade',
    bundled: true,
    group: 'creative',
    bold: false,
    italic: false,
    stack: `'Bungee Shade', ${ETHIOPIC}, cursive`,
  },
  caveat: {
    label: 'Caveat',
    family: 'Caveat',
    bundled: true,
    group: 'creative',
    bold: true,
    italic: false,
    stack: `'Caveat', ${ETHIOPIC}, cursive`,
  },
  'caveat-brush': {
    label: 'Caveat Brush',
    family: 'Caveat Brush',
    bundled: true,
    group: 'creative',
    bold: false,
    italic: false,
    stack: `'Caveat Brush', ${ETHIOPIC}, cursive`,
  },
  elsie: {
    label: 'Elsie',
    family: 'Elsie',
    bundled: true,
    group: 'creative',
    bold: true,
    italic: false,
    stack: `'Elsie', ${ETHIOPIC}, cursive`,
  },
  lobster: {
    label: 'Lobster',
    family: 'Lobster',
    bundled: true,
    group: 'creative',
    bold: false,
    italic: false,
    stack: `'Lobster', ${ETHIOPIC}, cursive`,
  },
  pacifico: {
    label: 'Pacifico',
    family: 'Pacifico',
    bundled: true,
    group: 'creative',
    bold: false,
    italic: false,
    stack: `'Pacifico', ${ETHIOPIC}, cursive`,
  },
  parisienne: {
    label: 'Parisienne',
    family: 'Parisienne',
    bundled: true,
    group: 'creative',
    bold: false,
    italic: false,
    stack: `'Parisienne', ${ETHIOPIC}, cursive`,
  },
  vibur: {
    label: 'Vibur',
    family: 'Vibur',
    bundled: true,
    group: 'creative',
    bold: false,
    italic: false,
    stack: `'Vibur', ${ETHIOPIC}, cursive`,
  },
};

type FontChoice = { font: FontKey; headingFont: FontKey | 'same'; nameFont: AnyFontKey | 'same' };
/** The headings' font: their own choice, else the text font. */
export const headingFontOf = (d: FontChoice): FontKey =>
  d.headingFont === 'same' ? d.font : d.headingFont;
/** The name's font: its own choice, else the heading font, else the text font. */
export const nameFontOf = (d: FontChoice): AnyFontKey =>
  d.nameFont === 'same' ? headingFontOf(d) : d.nameFont;
